language: java
branches:
  only:
    - develop
    - /^release-[0-999].[0-999]$/
    - master
notifications:
  email:
    recipients:
      - apawupm@outlook.es
script:
  #Test unitario y de integracion con cobertura
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify

#SONARCLOUD
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=diegoriofrio-github -Dsonar.login=$SONAR

#Deploy https://apaw-ep-robinson-diego.herokuapp.com/api
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU
  on:
    branch: master
  app: apaw-ep-robinson-diego
